### ISSUE TITLE
database and mos

### ISSUE THREAD

**Issue by M-ZFang** [ZhengyuZhang96/DeeBLiF#1]
Could you please give me a copy of the original image dataset? And how did you obtain mos?

**Comment by ZhengyuZhang96** [comment]
Hi,

Thank you for your interest in our work! All MOSs are provided in the original dataset.
For Win5-LID dataset, please refer to: http://staff.ustc.edu.cn/~chenzhibo/resources/2018/win5_lid.html
For NBU-LF1.0 and SHU datasets, please make a request to the authors of the corresponding paper.

Regard,
Zhengyu
